services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $projectDir: '%kernel.project_dir%'
      $contaoInsertTagParser: '@contao.insert_tag.parser'

  Markocupic\ExportTable\:
    resource: ../src/
    exclude: ../src/{Model,DependencyInjection,Resources}

  # Inject the default CSV writer into Markocupic\ExportTable\Export\ExportTable and Markocupic\ExportTable\DataContainer\ExportTable during compilation
  Markocupic\ExportTable\Writer\CsvWriter:
    tags:
      - { name: markocupic_export_table.writer, alias: csv, verbose_name: Default csv exporter class }

  # Inject the default XML writer into Markocupic\ExportTable\Export\ExportTable and Markocupic\ExportTable\DataContainer\ExportTable during compilation
  Markocupic\ExportTable\Writer\XmlWriter:
    tags:
      - { name: markocupic_export_table.writer, alias: xml, verbose_name: Default xml exporter class }
